[book]
title = "dotfiles"
authors = [ "Davide Peressoni" ]
description = "My literate dotfiles for Nix"
language = "en"
src = "src"

[output.html]
smart-punctuation = true
git-repository-url = "https://gitlab.com/DPDmancul/dotfiles"
git-repository-icon = "fab-gitlab"
edit-url-template = "https://gitlab.com/DPDmancul/dotfiles/blob/nix/{path}"
additional-css = [ "theme/mdbook-code-position.css" ]

[preprocessor.code-position]
command = "./mdbook-code-position"

