#+TITLE: git configuration
#+AUTHOR: Davide Peressoni
#+KEYWORDS: git config

* git config
:PROPERTIES:
:header-args: :tangle ~/.config/git/config
:header-args+: :mkdirp yes
:END:

** User config

#+BEGIN_SRC conf
[user]
  name = DPDmancul
  email = davide.peressoni@tuta.io
#+END_SRC

** Core config

#+BEGIN_SRC conf
[core]
#+END_SRC

*** Global ignore file

I'm using the default =~/.config/git/ignore= so no need to set this explicitly.

#+BEGIN_SRC conf :tangle no
  excludesfile = ~/.config/git/ignore
#+END_SRC

*** CR/LF

Fix EOL for files written under Windows.

#+BEGIN_SRC conf
  autocrlf = input
#+END_SRC

** Init

#+begin_src conf
[init]
#+end_src

*** Default branch

When creating a new repo, set the default branch to =main=.

#+begin_src conf
        defaultBranch = main
#+end_src

** Status

#+begin_src conf
[status]
#+end_src

*** Untracked files

Show also individual files in untracked directories.

#+begin_src conf
  showUntrackedFiles = all
#+end_src

*** Submodule summary

Enable submodule summary showing the summary of commits for modified submodules.

#+begin_src conf
  submoduleSummary = true
#+end_src

** Fetching

#+begin_src conf
[fetch]
#+end_src

*** Prune

Prune the local tracking branches and tags when fetching from remote.

#+begin_src conf
  prune = true
  pruneTags = true
#+end_src

** Pull

#+begin_src conf
[pull]
#+end_src

*** Fast-forward only

When pulling only update the current branch by fast-forwarding.

#+begin_src conf
  ff = only
#+end_src

** COMMENT Rerere

git-rerere stands for: Reuse recorded resolution of conflicted merges.
It is an awesome feature that helps you to resolve the same conflicts over and over again.

#+BEGIN_SRC conf
[rerere]
  enabled = true
#+END_SRC

** Diff

*** Delta

Delta enhance your git diff output by adding some cool features like syntax highlighting, line numbering, and side-by-side view.

#+begin_src conf :tangle ~/.config/git/config :mkdirp yes
[core]
  pager = delta
[interactive]
  diffFilter = delta --color-only --features=interactive
[delta]
  # side-by-side = true
  wrap-max-lines = unlimited
  max-line-length = 2048
  syntax-theme = gruvbox-light
#+end_src

To choose a theme run:
#+begin_src sh :tangle no
delta --list-syntax-themes
#+end_src

*** Better OrgMode diff

Recognizes Org headers in diff.

#+begin_src conf
[diff "org"]
  xfuncname = "^ *\\*{1,6}[ \\t].*"
#+end_src

** LFS

These settings involving LFS are generated by git itself.

#+BEGIN_SRC conf
[filter "lfs"]
  smudge = git-lfs smudge -- %f
  process = git-lfs filter-process
  required = true
  clean = git-lfs clean -- %f
#+END_SRC

** Protocol

Enable git protocol version 2.

Read [[https://about.gitlab.com/2018/12/10/git-protocol-v2-enabled-for-ssh-on-gitlab-dot-com/][about it]].

#+BEGIN_SRC conf
[protocol]
  version = 2
#+END_SRC

** Credential helper

Use Bitwarden as credential helper (see [[https://github.com/bitwarden/cli/pull/388]])

#+BEGIN_SRC conf
[credential]
  helper = bw
#+END_SRC

Requires Bitwarden CLI and

#+BEGIN_SRC sh :tangle no
curl https://raw.githubusercontent.com/bitwarden/cli/406c340e53e9bae9309ae40de2fb9bb570b8b082/scripts/git-credential-bw.sh > ~/.local/bin/git-credential-bw
chmod +x ~/.local/bin/git-credential-bw
#+END_SRC

** Sendmail

Configure git to send mails directly from git.

Instructions came from [[https://git-send-email.io/][git-send-email.io]].

# I have =msmtp= configured to send mails through Emacs, so I can just use that tool here too.

#+begin_src conf
# [sendemail]
#   smtpserver = /usr/bin/msmtp
#+end_src

* Global Gitignore
:PROPERTIES:
:header-args: :tangle ~/.config/git/ignore
:header-args+: :mkdirp yes
:END:

** CCLS LSP

For C code I'm using CCLS with LSP in emacs. Ignore the files this creates.

#+begin_src conf
.ccls-cache/
#+end_src

** Dir locals

Ignore personal Emacs [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html][=.dir-locals.el=]].

#+BEGIN_SRC conf
.dir-locals-2.el
#+END_SRC

** Direcotry file

#+BEGIN_SRC conf
.directory
#+END_SRC

** Code

#+BEGIN_SRC conf
.vscode
#+END_SRC

** Python cache

#+begin_src conf
__pycache__
.pytest_cache
#+end_src

** NextCloud

#+begin_src conf
.owncloudsync.log
._sync_*.db*
#+end_src


* Git attributes
:PROPERTIES:
:header-args: :tangle ~/.config/git/attributes
:header-args+: :mkdirp yes
:END:

Improve diff output for various file types.

From: https://tekin.co.uk/2020/10/better-git-diff-output-for-ruby-python-elixir-and-more

#+BEGIN_SRC conf
*.c     diff=cpp
*.h     diff=cpp
*.c++   diff=cpp
*.h++   diff=cpp
*.cpp   diff=cpp
*.hpp   diff=cpp
*.cc    diff=cpp
*.hh    diff=cpp
*.cs    diff=csharp
*.css   diff=css
*.html  diff=html
*.xhtml diff=html
*.ex    diff=elixir
*.exs   diff=elixir
*.go    diff=golang
*.php   diff=php
*.pl    diff=perl
*.py    diff=python
*.md    diff=markdown
*.rb    diff=ruby
*.rake  diff=ruby
*.rs    diff=rust
*.lisp  diff=lisp
*.el    diff=lisp
#+END_SRC
